package neu.edu.model;

// Generated Apr 26, 2011 6:48:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "COURSE")
public class Course implements java.io.Serializable {

	private int courseId;
	private String courseName;
	private int credit;
	private int capacity;
	private Instructor instructor;
	private Set<Student> students = new HashSet<Student>(0);

	public Course() {
	}

	public Course(String courseName, int credit, int capacity,
			Instructor instructor, Set<Student> students) {
		this.courseName = courseName;
		this.credit = credit;
		this.capacity = capacity;
		this.instructor = instructor;
		this.students = students;
	}

	@Id
	@GeneratedValue
	@Column(name = "COURSEID", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Column(name = "COURSENAME")
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "CREDIT")
	public int getCredit() {
		return this.credit;
	}

	public void setCredit(int credit) {
		this.credit = credit;
	}

	@Column(name = "CAPACITY")
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INSTRUCTORID")
	public Instructor getInstructor() {
		return this.instructor;
	}

	public void setInstructor(Instructor instructor) {
		this.instructor = instructor;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "STUDENT_COURSE", joinColumns = { @JoinColumn(name = "COURSEID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "STUDENTID", nullable = false, updatable = false) })
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
