package neu.edu.model;

// Generated Apr 26, 2011 6:48:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instructor generated by hbm2java
 */
@Entity
@Table(name = "INSTRUCTOR")
public class Instructor implements java.io.Serializable {

	private int instructorId;
	private String instructorName;
	private String email;
	private String password;
	private Set<Course> courses = new HashSet<Course>(0);

	public Instructor() {
	}

	public Instructor(String instructorName, String email, String password,
			Set<Course> courses) {
		this.instructorName = instructorName;
		this.email = email;
		this.password = password;
		this.courses = courses;
	}

	@Id
	@GeneratedValue
	@Column(name = "INSTRUCTORID", nullable = false)
	public int getInstructorId() {
		return this.instructorId;
	}

	public void setInstructorId(int instructorId) {
		this.instructorId = instructorId;
	}

	@Column(name = "INSTRUCTORNAME")
	public String getInstructorName() {
		return this.instructorName;
	}

	public void setInstructorName(String instructorName) {
		this.instructorName = instructorName;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinColumn(name = "INSTRUCTORID", updatable = false)
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
